CREATE TABLE IF NOT EXISTS public.player
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    years INTEGER NOT NULL,
    experience INTEGER NOT NULL,
    team_id INTEGER REFERENCES public.team(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS player_first_last_un_idx
    ON public.player (first_name, last_name);